- name: copy env file...
  copy: src=docker.env dest=~/docker.env

- include: redis.yml
- include: postgres.yml
- include: mysql.yml
- include: server-psql.yml
- include: server-mysql.yml
- include: frontend.yml