- name: build shintech-server-psql container...
  docker_container:
    name: shintech-server-psql
    image: shintech/shintech-server-psql
    state: started
    restart: yes
    network_mode: bridge
    env_file: "{{ environment_file }}"
    env:
      PORT: 55460
    ports:
      - "55460:55460"    
    networks:
      - name: "{{ network_name }}"
      